name: Discord notification on PR review request and PR review submission

on:
  # Triggers the workflow on PR request and submitted review
  pull_request:
    types: [review_requested]
  pull_request_review:
    types: [submitted]
  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Discord notification
    steps:
      - name: Review requested
        uses: Ilshidur/action-discord@master
        if: github.event.action == 'review_requested'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"PR Review Requested!", "color": 39423, "url":${{ toJSON(github.event.pull_request.html_url) }},"description": "${{ github.event.pull_request.user.login}} requested a review from ${{github.event.requested_reviewer.login}} for the PR: ${{github.event.pull_request.title}}"  }]'
        with:
          args: ''
      - name: Review submitted
        uses: Ilshidur/action-discord@master
        if: github.event.action == 'submitted'
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"PR Review Submitted - ${{github.event.user.pull_request.state}}", "color": ${{ (github.event.review.state == approved && 65280) || 16744192 }}, "url":${{ toJSON(github.event.review.html_url) }},"description": "${{github.event.user.pull_request.login}}, ${{ github.event.review.user.login}} submitted a review for your PR:${{github.event.pull_request.title}}"  }]'
        with:
          args: ''
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ (github.event.review.state == 'commented' && 'comment") || "not comment" }}'
