name: Discord notification on PR request and 

on:
  # Triggers the workflow on PR request and submitted review
  pull_request:
    types: [review_requested, opened, closed, reopened]
  pull_request_review:
    types: [submitted]
  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Discord notification
    steps:
      - name: Sending message
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"PR Review Requested!", "url":${{ toJSON(github.event.pull_request.url) }},"description":${{ toJSON(github.event.pull_request.user.login) }}}]'
        with:
          args: ''
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ github.event.pull_request.url }}'
