name: Discord notification on PR request and 

on:
  # Triggers the workflow on PR request and submitted review
  pull_request:
    types: [review_requested]
  #pull_request_review:
    #types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Discord notification
    steps:
      - name: Sending message
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '{{ EVENT_PAYLOAD.pull_request.user.login }} has requested a review from {{ EVENT_PAYLOAD.requested_reviewer.login }} for the PR: {{ EVENT_PAYLOAD.pull_request.title }}'
