name: Discord notification on PR review request and PR review submission

on:
  # Triggers the workflow on PR request and submitted review
  pull_request:
    types: [review_requested]
  pull_request_review:
    types: [submitted]
  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Discord notification
    steps:
      - name: Review requested
        uses: Ilshidur/action-discord@master
        if: github.event.action == 'review_requested'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"PR Review Requested!", "color": 39423, "url":${{ toJSON(github.event.pull_request.html_url) }},"description": "${{ github.event.pull_request.user.login}} requested a review from ${{github.event.requested_reviewer.login}} for the PR: [${{github.event.pull_request.title}}]"  }]'
        with:
          args: ''
      - name: Review submitted - Approved 
        uses: Ilshidur/action-discord@master
        if: github.event.action == 'submitted' && github.event.review.state == 'approved'
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"PR Review Submitted - Approved", "color": 65280, "url":${{ toJSON(github.event.review.html_url) }},"description": "${{github.event.pull_request.user.login}}, ${{ github.event.review.user.login}} submitted a review for your PR: [${{github.event.pull_request.title}}]"  }]'
        with:
          args: ''
      - name: Review submitted - Commented
        uses: Ilshidur/action-discord@master
        if: github.event.action == 'submitted' && github.event.review.state == 'commented'
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"PR Review Submitted - Commented", "color": 16776960, "url":${{ toJSON(github.event.review.html_url) }},"description": "${{github.event.pull_request.user.login}}, ${{ github.event.review.user.login}} submitted a review for your PR: [${{github.event.pull_request.title}}]"  }]'
        with:
          args: ''
      - name: Review submitted - Changes Requested
        uses: Ilshidur/action-discord@master
        if: github.event.action == 'submitted' && github.event.review.state == 'changes_requested'
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"PR Review Submitted - Changes Requested", "color": 16744192, "url":${{ toJSON(github.event.review.html_url) }},"description": "${{github.event.pull_request.user.login}}, ${{ github.event.review.user.login}} submitted a review for your PR: [${{github.event.pull_request.title}}]"  }]'
        with:
          args: ''

